name: NoteblockPlugin
version: '${version}'
main: me.aneleu.noteblockplugin.NoteblockPlugin
api-version: '1.20'
commands:
  noteblock:
    description: Create Song / Generate Noteblock
    aliases:
      - nb
      - n